import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import Footer from '@/components/Footer';



export const metadata: Metadata = {
  title: 'Zach Gallman SWE Portfolio',
  description: 'Personal portfolio generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="eng">
      <Header />
      <body className="pt-10 mt-5">{children}</body>
      <Footer />
    </html>
  )
}
